Consume Secure Flag On New Address Reported
ONSdigital/census-rm-fieldwork-adapter pull request #60
Opened 2020-09-24 09:02 UTC by LeoKHoward

# Motivation and Context
We want to record a property as secure so that future visits can be arranged if required

# What has changed
secureEstablishment flag changed from object to primitive type so it cannot be null
Updated tests

# How to test?
Build with other branches on card and run ATs

# Links
https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=40216113

2020-09-24 09:26 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Consume secure flag on newAddressReported (5)](https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5)

2020-09-24 13:21 UTC, NickGrantONS requested changes
You have introduced the possibility of a null pointer exception into `CaseReceiver`

This line: `actionInstruction.setSecureEstablishment(caze.getMetadata().getSecureEstablishment());`

2020-09-24 13:22 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtActionInstruction.java
> +  private boolean secureEstablishment;
This change will cause null pointer exceptions. See other comment

2020-10-02 11:42 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Consume secure flag on newAddressReported (5)](https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5)

2020-10-02 13:20 UTC, NickGrantONS approved these changes
Good

2020-10-04 17:43 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Consume secure flag on newAddressReported (5)](https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5)

2020-10-05 10:56 UTC, NickGrantONS approved these changes
This looks fine

2020-10-06 08:08 UTC, ryangrundy7 approved these changes

2020-10-06 10:32 UTC, merged